In [49]:
import cv2
import numpy as np
vidcap = cv2.VideoCapture("C:/Users/user/Desktop/DeepLabCut-master/examples/Dystonia_Test-Diogo_2022_04_21/videos/42136_RF_W01VideoProcessed2021-12-07T12_11_59.avi")

In [50]:
vidcap.set(1,0)
ret, frame = vidcap.read()
previousFrame = frame
previousFrame #get the first previousFrame (frame 0) which will be fed into the following loop

array([[[121, 121, 121],
        [121, 121, 121],
        [121, 121, 121],
        ...,
        [149, 149, 149],
        [149, 149, 149],
        [149, 149, 149]],

       [[121, 121, 121],
        [121, 121, 121],
        [121, 121, 121],
        ...,
        [149, 149, 149],
        [149, 149, 149],
        [149, 149, 149]],

       [[121, 121, 121],
        [121, 121, 121],
        [121, 121, 121],
        ...,
        [149, 149, 149],
        [149, 149, 149],
        [149, 149, 149]],

       ...,

       [[203, 203, 203],
        [203, 203, 203],
        [203, 203, 203],
        ...,
        [128, 128, 128],
        [128, 128, 128],
        [128, 128, 128]],

       [[211, 211, 211],
        [211, 211, 211],
        [211, 211, 211],
        ...,
        [128, 128, 128],
        [128, 128, 128],
        [128, 128, 128]],

       [[215, 215, 215],
        [215, 215, 215],
        [215, 215, 215],
        ...,
        [128, 128, 128],
        [128, 128, 128],
        [128, 128, 128]]

In [51]:
previousFrame.shape

(716, 896, 3)

In [52]:
total_frames = vidcap.get(7)
total_frames

18864.0

There is pattern of noise in the data.
I will attempt a similar approach but using summing zeros and ones rather than the true value of pixel change.

I will create a temporary cutOff, using the average of 3 cutOff randomly selected from the video (go to the array containing the px changes and see the distribution of each a.flatten() array; obtain the kdeplot, significant local minimum, get the x valu of the local minimum, set it as cutOff)

In [148]:
import numpy as np

randnums= np.random.randint(0,total_frames,3)

randnums

array([11404,  7301,  2935])

In [137]:
vidcap.set(1,0)
ret, frame = vidcap.read()
frame0 = frame

vidcap.set(1, 1)
ret, frame = vidcap.read()
frame_1 = frame

In [138]:
for fr in range(len(frame0.flatten() == frame_menos1.flatten())):
    print((frame0.flatten()==frame_1.flatten())[fr])

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
False
False
True
True
True
True
True
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
True
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
True
True
False
False
False
True
True
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
True
True
True
True
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
T

KeyboardInterrupt: 

In [210]:
vidcap.set(1,0)
ret, frame = vidcap.read()
previousFrame = frame
previousFrame #get the first previousFrame (frame -1) which will be fed into the following loop

array([[[121, 121, 121],
        [121, 121, 121],
        [121, 121, 121],
        ...,
        [149, 149, 149],
        [149, 149, 149],
        [149, 149, 149]],

       [[121, 121, 121],
        [121, 121, 121],
        [121, 121, 121],
        ...,
        [149, 149, 149],
        [149, 149, 149],
        [149, 149, 149]],

       [[121, 121, 121],
        [121, 121, 121],
        [121, 121, 121],
        ...,
        [149, 149, 149],
        [149, 149, 149],
        [149, 149, 149]],

       ...,

       [[203, 203, 203],
        [203, 203, 203],
        [203, 203, 203],
        ...,
        [128, 128, 128],
        [128, 128, 128],
        [128, 128, 128]],

       [[211, 211, 211],
        [211, 211, 211],
        [211, 211, 211],
        ...,
        [128, 128, 128],
        [128, 128, 128],
        [128, 128, 128]],

       [[215, 215, 215],
        [215, 215, 215],
        [215, 215, 215],
        ...,
        [128, 128, 128],
        [128, 128, 128],
        [128, 128, 128]]

In [190]:
plt.hist(np.log(a.flatten()+1),bins=10)

(array([5.38197e+05, 6.67630e+04, 2.65850e+04, 3.51700e+03, 2.43400e+03,
        1.35800e+03, 9.39000e+02, 7.38000e+02, 6.81000e+02, 3.24000e+02]),
 array([0.        , 0.47361984, 0.94723969, 1.42085953, 1.89447938,
        2.36809922, 2.84171907, 3.31533891, 3.78895876, 4.2625786 ,
        4.73619845]),
 <BarContainer object of 10 artists>)

In [198]:
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

arr_cutOffs = []
video_px_change_sum_nonzeros = []

#for fr in range(1, int(total_frames)):
for fr in range(1,11):
    vidcap.set(1,fr)
    ret, frame = vidcap.read()
    print(fr)

    if fr in randnums:
        a = np.absolute(np.subtract(frame.astype(int)[:,:,0], previousFrame.astype(int)[:,:,0]))
        dist_log = sns.kdeplot(a.flatten()+0.00001, log_scale=True).lines[0]

        x = dist_log.get_data()[0]
        y = dist_log.get_data()[1]

        previousFrame = frame

        peaks = np.where((y_c[1:-1] > y_c[0:-2]) * (y_c[1:-1] > y_c[2:]))[0] + 1
        dips = np.where((y_c[1:-1] < y_c[0:-2]) * (y_c[1:-1] < y_c[2:]))[0] + 1

        #save the x coordinate of each of the three local mininum
        for dip in range(len(dips)):
            arr_cutOffs.append(x[dip])

#obtain the average cutOff
if average_cutOff > 0:
    average_cutOff = np.mean(arr_cutOffs)

1
2
3
4
5
6
7
8
9
10


---

In [223]:
px_change_filtered = []
sum_above_cutOff = 0
cutOff_temp = 20

for fr in range(1, int(total_frames)): #from 0 to 18863
    vidcap.set(1,fr)
    ret, frame = vidcap.read()
    a = np.absolute(np.subtract(frame.astype(int)[:,:,0], previousFrame.astype(int)[:,:,0]))
        
    occurences_above_cutoff = a.flatten()>50 #TRY HIGHER CUTOFF!!
    value_per_frame = occurences_above_cutoff.sum()
    
    px_change_filtered.append(value_per_frame)
    
    #after performing the operation, 'frame' will get a new value and the currentFrame of this iteration will be the previous
    #...frame in the following iteration
    previousFrame = frame
    print(fr)

1


In [229]:
plt.plot(px_change_filtered)

In [239]:
vidcap.set(1,0)
ret, frame = vidcap.read()
previousFrame = frame
previousFrame #get the first previousFrame (frame 0) which will be fed into the following loop

array([[[121, 121, 121],
        [121, 121, 121],
        [121, 121, 121],
        ...,
        [149, 149, 149],
        [149, 149, 149],
        [149, 149, 149]],

       [[121, 121, 121],
        [121, 121, 121],
        [121, 121, 121],
        ...,
        [149, 149, 149],
        [149, 149, 149],
        [149, 149, 149]],

       [[121, 121, 121],
        [121, 121, 121],
        [121, 121, 121],
        ...,
        [149, 149, 149],
        [149, 149, 149],
        [149, 149, 149]],

       ...,

       [[203, 203, 203],
        [203, 203, 203],
        [203, 203, 203],
        ...,
        [128, 128, 128],
        [128, 128, 128],
        [128, 128, 128]],

       [[211, 211, 211],
        [211, 211, 211],
        [211, 211, 211],
        ...,
        [128, 128, 128],
        [128, 128, 128],
        [128, 128, 128]],

       [[215, 215, 215],
        [215, 215, 215],
        [215, 215, 215],
        ...,
        [128, 128, 128],
        [128, 128, 128],
        [128, 128, 128]]

In [240]:
for fr in range(1,2): #from 0 to 18863
    vidcap.set(1,fr)
    ret, frame = vidcap.read()
    a = np.absolute(np.subtract(frame.astype(int)[:,:,0], previousFrame.astype(int)[:,:,0]))
   
    plt.plot(a.flatten())
    
    #after performing the operation, 'frame' will get a new value and the currentFrame of this iteration will be the previous
    #...frame in the following iteration
    previousFrame = frame
    print(fr)

1
